# Generated by Django 4.1.1 on 2023-01-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='branch',
            new_name='name_branch',
        ),
        migrations.RemoveField(
            model_name='details',
            name='address',
        ),
        migrations.RemoveField(
            model_name='details',
            name='age',
        ),
        migrations.RemoveField(
            model_name='details',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='details',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='details',
            name='email',
        ),
        migrations.RemoveField(
            model_name='details',
            name='name',
        ),
    ]
