# Generated by Django 4.1.1 on 2023-01-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_rename_branch_details_name_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='name_branch',
            new_name='district',
        ),
        migrations.AddField(
            model_name='details',
            name='name',
            field=models.CharField(default=23, max_length=250),
            preserve_default=False,
        ),
    ]
