# Generated by Django 4.1.1 on 2023-03-10 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_rename_name_branch_details_district_details_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Acc_type',
        ),
        migrations.AddField(
            model_name='district',
            name='slug',
            field=models.SlugField(default=0.0016477179106936892, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.AddField(
            model_name='district',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='credentials.branches'),
            preserve_default=False,
        ),
    ]
