# Generated by Django 4.1.1 on 2023-01-28 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_inputform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InputForm',
        ),
    ]
